name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## What's Changed
            
            - See [CHANGELOG.md](CHANGELOG.md) for detailed changes
            
            ## Installation
            
            ### Quick Install
            ```bash
            curl -sSL https://raw.githubusercontent.com/twilson63/lmdb-tree-viewer/main/install.sh | bash
            ```
            
            ### Manual Install
            1. Download the appropriate binary for your platform below
            2. Extract the archive
            3. Make it executable: `chmod +x lmdb-tree-viewer`
            4. Move to your PATH: `mv lmdb-tree-viewer /usr/local/bin/`
            
            ### Requirements
            - **mdb_dump**: LMDB utilities package
              - macOS: `brew install lmdb`
              - Ubuntu/Debian: `apt-get install lmdb-utils`
              - CentOS/RHEL: `yum install lmdb-utils`
            
            ## Usage
            
            ```bash
            # Full tree visualization
            mdb_dump /path/to/database.lmdb | lmdb-tree-viewer
            
            # Summary mode
            mdb_dump /path/to/database.lmdb | lmdb-tree-viewer --summary
            ```
          files: |
            lmdb-tree-viewer*
            *.tar.gz
            *.zip
          draft: false
          prerelease: false

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3
      
      - name: Create Linux Binary
        run: |
          mkdir -p dist
          
          # Create wrapper script
          cat > dist/lmdb-tree-viewer << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          lua "$SCRIPT_DIR/lmdb-tree-viewer.lua" "$@"
          EOF
          
          # Copy the Lua script
          cp lmdb-tree-viewer.lua dist/
          
          # Make executable
          chmod +x dist/lmdb-tree-viewer
          
          # Create archive
          cd dist
          tar -czf ../lmdb-tree-viewer-linux.tar.gz .
      
      - name: Upload Linux Archive
        uses: softprops/action-gh-release@v1
        with:
          files: lmdb-tree-viewer-linux.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          brew install lua
      
      - name: Create macOS Binary
        run: |
          mkdir -p dist
          
          # Create wrapper script
          cat > dist/lmdb-tree-viewer << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          lua "$SCRIPT_DIR/lmdb-tree-viewer.lua" "$@"
          EOF
          
          # Copy the Lua script
          cp lmdb-tree-viewer.lua dist/
          
          # Make executable
          chmod +x dist/lmdb-tree-viewer
          
          # Create archive
          cd dist
          tar -czf ../lmdb-tree-viewer-macos.tar.gz .
      
      - name: Upload macOS Archive
        uses: softprops/action-gh-release@v1
        with:
          files: lmdb-tree-viewer-macos.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          choco install lua
      
      - name: Create Windows Binary
        run: |
          mkdir dist
          
          # Create wrapper batch file
          @'
          @echo off
          set SCRIPT_DIR=%~dp0
          lua "%SCRIPT_DIR%\lmdb-tree-viewer.lua" %*
          '@ | Out-File -FilePath dist/lmdb-tree-viewer.bat -Encoding ascii
          
          # Copy the Lua script
          copy lmdb-tree-viewer.lua dist/
          
          # Create archive
          cd dist
          7z a ../lmdb-tree-viewer-windows.zip .
      
      - name: Upload Windows Archive
        uses: softprops/action-gh-release@v1
        with:
          files: lmdb-tree-viewer-windows.zip