name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## What's Changed
            
            - See [CHANGELOG.md](CHANGELOG.md) for detailed changes
            
            ## Installation
            
            ### Quick Install
            ```bash
            curl -sSL https://raw.githubusercontent.com/twilson63/lmdb-tree-viewer/main/install.sh | bash
            ```
            
            ### Manual Install
            1. Download the appropriate binary for your platform below
            2. Make it executable: `chmod +x lmdb-tree-viewer`
            3. Move to your PATH: `mv lmdb-tree-viewer /usr/local/bin/`
            
            ### Requirements
            - **mdb_dump**: LMDB utilities package
              - macOS: `brew install lmdb`
              - Ubuntu/Debian: `apt-get install lmdb-utils`
              - CentOS/RHEL: `yum install lmdb-utils`
            
            ## Usage
            
            ```bash
            # Full tree visualization
            mdb_dump /path/to/database.lmdb | lmdb-tree-viewer
            
            # Summary mode
            mdb_dump /path/to/database.lmdb | lmdb-tree-viewer --summary
            ```
          draft: false
          prerelease: false

  build-binaries:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: linux-amd64
            goos: linux
            goarch: amd64
          - target: linux-arm64
            goos: linux
            goarch: arm64
          - target: darwin-amd64
            goos: darwin
            goarch: amd64
          - target: darwin-arm64
            goos: darwin
            goarch: arm64
          - target: windows-amd64
            goos: windows
            goarch: amd64

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      
      - name: Build Hype Runtime
        run: |
          # Clone hype repository to get the runtime
          git clone https://github.com/twilson63/hype.git hype-source
          cd hype-source
          
          # Build hype for the host platform (Linux amd64) to run the build process
          go build -o ../hype .
          
          cd ..
          rm -rf hype-source
      
      - name: Build Binary with Hype
        run: |
          # Set target extension
          EXT=""
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            EXT=".exe"
          fi
          
          # Build the binary using hype with cross-compilation
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} ./hype build lmdb-tree-viewer.lua -o lmdb-tree-viewer-${{ matrix.target }}${EXT}
          
          # Verify the binary was created
          ls -la lmdb-tree-viewer-${{ matrix.target }}${EXT}
      
      - name: Upload Binary
        uses: softprops/action-gh-release@v1
        with:
          files: lmdb-tree-viewer-${{ matrix.target }}${{ matrix.goos == 'windows' && '.exe' || '' }}